### ISSUE TITLE
Failed to resolve: com.github.SandroMachado:openalpr-android:1.1.0

### ISSUE THREAD

**Issue by dzordz55** [SandroMachado/openalpr-android#16]
Hi,
I have a problem with adding library in gradle. I get error: 
`Failed to resolve: com.github.SandroMachado:openalpr-android:1.1.0`

My project build.gradle:
`...
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}...
`
and module build.gradle:

`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    ...
    compile 'com.github.SandroMachado:openalpr-android:1.1.0'
    ...
}`
Can anyone help me?

**Comment by SandroMachado** [comment]
Hey @dzordz55,

can you please test it again? It is working here.
Looking for your configuration I don't find any bug...
But if you want, it is possible to double check the configurations here: https://jitpack.io/#SandroMachado/openalpr-android/1.1.1

**Comment by dzordz55** [comment]
I added library manually and it is working nice. I was using configuration like on jitpack.io.

**Comment by SandroMachado** [comment]
Thanks for the feedback.
