### ISSUE TITLE
No module found

### ISSUE THREAD

**Issue by ArunkarthickNallasamy** [SandroMachado/openalpr-android#17]
I imported openalpr-android into android studio but i don't find any module to run! How to configure it and run the sample in android studio!! I'm using android studio 2.1 preview 4!! If its silly I apologies but help me Please!!

**Comment by SandroMachado** [comment]
Hi @Arunkarthicknallasami,

you need to open the android studio from this directory: https://github.com/SandroMachado/openalpr-android/tree/master/Sample/OpenALPRSample to run the sample.

Please let me know if this works for you.

If you just want to check the sample, you can find the sample `APK` at the releases tab.

**Comment by ArunkarthickNallasamy** [comment]
Thank you its working!! I have one more doubt, Is it possible to recognize data with video stream instead of processing image after taking picture. If its not subjected to be asked over the issue coloumn i can email you my doubts.

**Comment by SandroMachado** [comment]
Unfortunately not, the library is only prepared to deal with static images.
