### ISSUE TITLE
Pass image as byte array not as file path

### ISSUE THREAD

**Issue by LosDanieloss** [SandroMachado/openalpr-android#18]
Hi,

Have you consider adding to your library possibility to pass image not as file path but using byte array? I am asking because I think that could speed up processing time in combination with own camera implementation. 

Regards,
Daniel

**Comment by SandroMachado** [comment]
Hi @LosDanieloss,

unfortunately not. My library is based on the [OpenALPR](https://github.com/openalpr/openalpr) and they only expose methods to pass the path of the image (https://github.com/SandroMachado/openalpr-android/blob/master/app/src/main/java/org/openalpr/AlprJNIWrapper.java). 

Regards,
Sandro Machado
