### ISSUE TITLE
Openalpr is Apache 2.0 but original openalpr is AGPL 3.0. Which license affects me?

### ISSUE THREAD

**Issue by mronnlun** [SandroMachado/openalpr-android#32]
If I want to use this library, which license affects me, only Apache 2.0 or is there actually a link to the original Openalpr that has AGPL 3.0 license?

**Comment by SandroMachado** [comment]
You need to consider the licence of the parent project [openalpr](https://github.com/openalpr/openalpr). So if you want to use this library and if you use any feature of this library that uses the parent project you need to consider the licence Affero GPLv3 http://www.gnu.org/licenses/agpl-3.0.html.
