### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by VSecur** [SandroMachado/openalpr-android#34]
Hello, what are the dependencies? How can I use your library in my Android Studio on Ubuntu / Linux? I've been researching a lot and it's very difficult to get something. If you can give me detailed instructions I will be very grateful.

**Comment by SandroMachado** [comment]
@VSecur you just need to follow the instructions available here: https://github.com/SandroMachado/openalpr-android#usage

You can also check the sample app available here: https://github.com/SandroMachado/openalpr-android/tree/master/Sample/OpenALPRSample

**Comment by VSecur** [comment]
Do I need OpenALPR? I was seeing other issues and I realized that if you want to use for Brazilian boards I need to recompile.

**Comment by SandroMachado** [comment]
Yup, the current version only supports US and EU.

**Comment by VSecur** [comment]
So should I compile following these instructions (https://github.com/openalpr/openalpr/wiki/Android-compilation) and copy the runtime_data folder with the files to Brazilian boards? Are you not interested in including the Brazilian standard in your library?

**Comment by SandroMachado** [comment]
Yes, you need to compile the library and move it to the `runtime_data` folder.

Yes, I really need to update to the latest version of openalpr, but unfortunately it is not easy and requires a lot of time. I also created an issue in the parent project to include the Android binaries for each release. You can do a `+1` in that issue, that will help a lot in the process of keeping this library sync with the parent project.
