### ISSUE TITLE
Upgrade the dependency `Libpng library` to allow submission to `Play Store`

### ISSUE THREAD

**Issue by SandroMachado** [SandroMachado/openalpr-android#35]
The `openalpr` binary is compile with a version of `libpng`  that contains security vulnerabilities for users or allows the collection of user data without proper disclosure.

Every app submitted for the `Play Store` using the library will be rejected, due to the new validation process that checks if the application contains code that has vulnerabilities.

**Comment by diarmuidryan** [comment]
i have been trying to update opencv lib to 3.1 but am getting this error now dlopen failed: cannot locate symbol "_ZTVN2cv11_InputArrayE" with upgraded lib

**Comment by lopezzbelgium** [comment]
+1 tried to do this but gave up because this required a lot more time than I can spend on it at the time. Still no one who was able to build everything with the new opencv?

**Comment by wicheda** [comment]
Has anyone made any progress on this, I am struggling with the same problem.
