### ISSUE TITLE
I don't know why it doesn't work...

### ISSUE THREAD

**Issue by thaiet** [SandroMachado/openalpr-android#36]
Hi there!
Great project but I can't seem to get it to work...I always get a result of  {"error":true,"msg":"Error initializing Open Alpr"}. 

In details,
My build.gradle (Project) contains the `allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}` 

I have `compile 'com.github.SandroMachado:openalpr-android:1.1.1' ` in my dependencies in the build.gradle (module:app). 

I also have the openalpr.conf, which I copied into the `assets/runtime_data/` directory of the app. I even used a copied version of your activity, but still the same error. Any ideas?

**Comment by SandroMachado** [comment]
Can you try the demo `apk` at the releases tab? Just to check if the compiled `apk` works?

**Comment by SandroMachado** [comment]
Closed due to inactivity.

**Comment by bipinbharti1357** [comment]
hello still i have error
