### ISSUE TITLE
Can I specify country settings in openalpr.config

### ISSUE THREAD

**Issue by mronnlun** [SandroMachado/openalpr-android#39]
Right now the settings are us and eu, and while I live in the eu and eu settings works ok for me, I wonder if I could specifiy a new country in openalpr.config with more detailed settings?

Additionally I wonder if I can specify the format of the license plate, because our format is ABC-123 and at the moment we see that the component sometimes detects O as 0.

**Comment by SandroMachado** [comment]
Hi @mronnlun,

it is not possible to add other countries without compiling the binaries. And also it is not possible to change the format.

Regards
