### ISSUE TITLE
Error initializing OpenALPR

### ISSUE THREAD

**Issue by kevinjpetersen** [SandroMachado/openalpr-android#42]
I'm trying to use this in my Android App, everything compiles correctly and the files DOES exists in the APK. I confirmed this by doing a InputStream to the Config file and then read it. I could do that no problem.

These are my paths to my files, and then at the bottom it says the error.

![image](https://cloud.githubusercontent.com/assets/1038017/23591144/57067c04-01ec-11e7-9503-58b7fa9d086b.png)

This is my Config file.

![image](https://cloud.githubusercontent.com/assets/1038017/23591151/8140e64e-01ec-11e7-9867-eed9c8da3f76.png)

This is my MainActivity

![image](https://cloud.githubusercontent.com/assets/1038017/23591164/a8cbe93e-01ec-11e7-9d20-f97c27024fd2.png)

What could go wrong?

**Comment by kevinjpetersen** [comment]
Appearently this method, doesn't actually work:

`OpenALPR.Factory.create(MainActivity.this, ANDROID_DATA_DIR).recognize(testImage, 10);`

Because when I change it to this:

`OpenALPR.Factory.create(MainActivity.this, ANDROID_DATA_DIR).recognizeWithCountryRegionNConfig("eu", "", testImage, openAlprConfFile, 10);`

It works like a charm

Closing.

**Comment by NoumanBaig** [comment]
Hi,
I got this error while i changed to india in config file.what can i do for that?
