### ISSUE TITLE
Multiple targets recognization

### ISSUE THREAD

**Issue by ChenKuanYu** [SandroMachado/openalpr-android#46]
I had tested the openalpr project that could recognize multiple license plates. And I think the openalpr-android project which you made is also designed for that purpose. But after I tested you app, I could only get one results at most while the openalpr project get two in the same photo. Is that normal?

**Comment by SandroMachado** [comment]
Hi @ChenKuanYu,

it should give more than one result. It can also be configured. Are using the same version of the openalpr in your other device that this library uses?

**Comment by ChenKuanYu** [comment]
No, I use the 2.3.0 version for the openalpr project, and use 1.1.2 version for the openalpr android project. I can get some similar result for a single license plate, but can't get results from different license plates. Where can it be configured?

**Comment by SandroMachado** [comment]
You cannot change that, and it does not makes sense comparing the results of two different versions. That is the reason for the difference in the results set.
