### ISSUE TITLE
Failed to resolve:com.github.SandroMachado:openalpr-android:1.1.2

### ISSUE THREAD

**Issue by stevenbp** [SandroMachado/openalpr-android#47]
![screen shot 2017-04-25 at 13 03 01](https://cloud.githubusercontent.com/assets/4764326/25382400/bb12798a-29b7-11e7-8c8b-08f61926ea05.png)

How can I fix this error?

**Comment by SandroMachado** [comment]
Add this to you main app `build.gradle`:

```
repositories {
    maven { url "https://jitpack.io" }
}
```

Check this: https://jitpack.io/#SandroMachado/openalpr-android/1.1.2
