### ISSUE TITLE
belgium plate 

### ISSUE THREAD

**Issue by Malcom100** [SandroMachado/openalpr-android#54]
The application can't recognize the belgium plate ex. formta : 1-ABC-235.

Is there an issue for that ?
Someone can help me ?

Thanks

**Comment by SandroMachado** [comment]
It should, can you please provide me an image?

**Comment by Malcom100** [comment]
I am sorry to answer too late, 
I solved my problem, I had to modify my runtime_dir in my file openalpr.conf with the good package name
