### ISSUE TITLE
ouldn't find "libopenalpr-native.so"

### ISSUE THREAD

**Issue by MgBoggy** [SandroMachado/openalpr-android#55]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.xross.aicar-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.xross.aicar-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libopenalpr-native.so"

I found this error when the app run on Android version 5.0.But it certainly work in Android Version 4.4. How should i solve.

**Comment by SandroMachado** [comment]
Are you using the demo app?

**Comment by SandroMachado** [comment]
Closed due to inactivity.
