### ISSUE TITLE
Support for indian number plate

### ISSUE THREAD

**Issue by Sumituppal-delhivery** [SandroMachado/openalpr-android#56]
Hi @SandroMachado 
I am stuck on indian number plates. 
Can you please help me to solve this problem.

**Comment by SandroMachado** [comment]
Hi @Sumituppal-delhivery.

this project only supports US and EU licence plates.

Regards

**Comment by Sumituppal-delhivery** [comment]
@SandroMachado Can you please me guide me how can i do it for indian licence plates.

**Comment by SandroMachado** [comment]
You need to check the parent project: https://github.com/openalpr/openalpr
