### ISSUE TITLE
Run time data

### ISSUE THREAD

**Issue by Avinash01111992** [SandroMachado/openalpr-android#64]
Hi I'm trying to add some extra trained images example parking number plate template. i trained Parking number plate image using tensorflow framework  and i exported the out put trained model as **.pb** file format.
**My question is if i have trained .pb model file how can use or add  my own trained image (template) with existing Eu?
Is this possible to do this?

**Comment by SandroMachado** [comment]
Hi @Avinash01111992,

I think it is not possible, but you should ask at the parent project: https://github.com/openalpr/openalpr

Regards
